version: '3.2'

services:
  pg:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - pg-data:/var/lib/postgresql/data

  app-smtp:
    image: djfarrelly/maildev:latest
    ports:
      - "8081:80"
      - "2525:25"

volumes:
  pg-data:
