version: '3.2'

services:
  pg:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - pg-data:/var/lib/postgresql/data

  smtp:
    image: djfarrelly/maildev:latest
    ports:
      - "8081:80"

  wci-be:
    image: janobono/wci-be:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://pg:5432/app
      - MAIL_HOST=smtp
      - MAIL_PORT=25
      - TOKEN_PRIVATE_KEY=MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAMEJLy2321vgOIKy/iR03qucOb0Ro3vlGgG8XV3Hw722Rw7+Yypr5tV7ewkvoSLfBXPj73o52dklHcALBLV0Nk8qBTqNUfvqpZi8qFygR8mLMxdluzOkurXPfpGDBL49r7+5Qf/ZnocyhNmdETFvDrw9ObQohwQNttIxyX9UFqUnAgMBAAECgYBEa3nybXFtzjqZcNINn/Lwxq3cau0UU+704IwDWnPxwTLMiLQjbB1kW6EPb3dgwcXP/uF55BloEvTJhd5EZo18whzMOui10KRMyzDE9QC6kD6Z47IsivLaLMv6WAbUv6YLbuqii/4zZVo7t6aDsxuOHmx5X8YS7K8w4ox5cAzYYQJBAOLNOUvmjw8xiZCIeQCI1d5fCQd84wgtZZUeobuf+ig/BUmDD8V6m6+PZqSI/r3GrVfX7E18DnmKWkYSSFl/ONECQQDZ4yFzRFZ7OCKHxD1E2b97OOqJWxC2TZRLuDulN2sQcHDaB18uuZwlNbAjFJZB+wVdBCanLKclqCL0OD7PDnx3AkEAgP1JHfLV4EVDQNFtSDGKuTsBrqGHmcn/4SyXvVcB9kvJXQLOQHk3/EQpk2BayWIqijBCs9rffJ6EMyAIx+XEUQJBALoXH8mXsxj4H52+/+ke5Eh0mvOHIGXjKmXlSqPYCgv3TJsaMrPweKjbCr1bZt2ha7o+wliDbZpe2MOmihZDtA8CQQCaGbInRVWw9IG7MCvKGLCG6sLUhTd4ZWSuE6MXdfpRw1U9cmtwIewjhJMvprRacwyYpBh7Xt3RwORZphvAWTsO
      - TOKEN_PUBLIC_KEY=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBCS8tt9tb4DiCsv4kdN6rnDm9EaN75RoBvF1dx8O9tkcO/mMqa+bVe3sJL6Ei3wVz4+96OdnZJR3ACwS1dDZPKgU6jVH76qWYvKhcoEfJizMXZbszpLq1z36RgwS+Pa+/uUH/2Z6HMoTZnRExbw68PTm0KIcEDbbSMcl/VBalJwIDAQAB
      - APPLICATION_NAME=WCI Docker Compose
      - APP_LANGUAGE_0=sk
      - APP_LANGUAGE_1=en
    depends_on:
      - pg
      - smtp

volumes:
  pg-data:
